import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import Navigation from '@/components/Navigation';
import AuthProvider from '@/context/AuthProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'StyroAI',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
      </head>
      <AuthProvider>
      <body className="overflow-x-hidden">
        <Navigation/>
      {children}
      </body>
      </AuthProvider>
    </html>

  );
}
