import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import Navigation from '@/components/Navigation';
import Providers from "./Providers";

const inter = Inter({ subsets: ['latin'] });
import { SessionProvider } from "next-auth/react"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className="overflow-hidden">
        <Navigation/>
      {children}
      </body>
    </html>

  );
}
